### ISSUE TITLE
broke again

### ISSUE THREAD

**Issue by skrill-on-discord** [xChonkster/roblox-internal-studio-patcher#3]
you should add docs to this or something so I can just make a pull request instead of an issue

**Comment by xch0nky** [comment]
crazy
it still works for me? whats your studio version

**Comment by skrill-on-discord** [comment]
version-5b3f6503f0e243c9

**Comment by skrill-on-discord** [comment]
wait wtf

**Comment by skrill-on-discord** [comment]
it just worked

**Comment by skrill-on-discord** [comment]
💀
